// import "../app/styles/globals.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hris | HR Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
